version: 2
jobs:
  build:
    working_directory: /var/www
    docker:
      - image: node:10.16.0-alpine
        environment:
          NODE_ENV: test
      - image: circleci/redis
      - image: memcached
    environment:
      TZ: "/usr/share/zoneinfo/Etc/UTC"
    steps:
      - checkout
      - run: npm install
      - run: npm audit
      - run: npm run lint
      - run: npm test
