version: 2
jobs:
  build:
    docker:
      - image: node:10.16.0-alpine
        environment:
          NODE_ENV: test
      # - image: circleci/redis
      # - image: memcached
    steps:
      - checkout
      - run: npm install
      - run: npm audit
      - run: npm run lint
      - run: npm test
